### ISSUE TITLE
Implement Percent Change on Locks 

### ISSUE THREAD

**Issue by rxxndy** [yours-org/frontend#1]
Implement percent change 24hr in Locked Coins component

View design specs here: https://www.figma.com/file/1zKUFyR2UvUa16Lu5T8IFb/Yours?type=design&node-id=521%3A11791&mode=design&t=IAEDYeK5mPXdM9ts-1

![Screenshot 2024-02-12 at 11 20 43 AM](https://github.com/yours-org/frontend/assets/48290359/bbd8c616-a6a3-4187-b196-db296ca84e71)

**Comment by utxo-detective** [comment]
done
