### ISSUE TITLE
Top lockers API request

### ISSUE THREAD

**Issue by jadwahab** [yours-org/frontend#7]
Hey, good stuff on the site so far!

Do you have an API endpoint at https://lock.yours.org that I can use to get the top locked addresses? I'm currently using only data from hodlocker for the top lockers chat but would like to use all locked content. Just need a mapping between address/publickey(hash) and amount of coins locked

**Comment by stevenzeiler** [comment]
```
GET https://yours.org/api/lockers
{
  lockers: {
    pubkeyhash: string,
    satoshis: number
  }[]
}
```

**Comment by utxo-detective** [comment]
Not yet. We are going to open source the entire backend soon but in the process of making it stable for more developers to work on it. At the current state it was hacked together and only built for the lock chart so im going to refactor it into a stronger foundation
